# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Crowhop Tech
# Description of the Site
description: Just a Crow and His Shinies
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Developer, Maker, Project
# URL for the Image of custom Favicon
# TODO: create and add favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/hero.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: akrpan@crowhop.tech
linkedin_username: adam-krpan
github_username:  CrowhopTech
youtube_channel_id: UC7SXjEidIb2cS4QdCYjyl5A
# reddit_username: /

# Google Analytics
# google-analytics: UA-163806439-1

author-name: Adam Krpan
author-image: /assets/images/profile.jpg
author-about: Software engineer, maker, and accumulator of projects, ideas, and shinies.
author-url: https://github.com/CrowhopTech

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
